# Test environment compose configuration



services:
  postgres:
    # Define postgres docker image
    image: 'postgres:15'
    ports:
      - '5432:5432'
    # Define data storage directory out of docker container
    # Before run postgres create directory for data
    # mkdir -p postgres-data
    # chmod 777 postgres-data
    volumes:
      - ./postgres-data:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=test
    restart: unless-stopped
  redis:
    image: redis:7
    ports:
      - '6379:6379'
    # Define data storage directory out of docker container
    # Before run postgres create directory for data
    # mkdir -p redis-data
    # chmod 777 redis-data
    volumes:
      - ./redis-data:/data
    environment:
      - REDIS_PASSWORD=password
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped