name: Backend CI

on:
  push:
    paths:
      - 'crm_backend/**'
  pull_request:
    paths:
      - 'crm_backend/**'

env:
  SPRING_PROFILES_ACTIVE: test

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Enable Docker host access
        run: |
          echo "DOCKER_HOST=unix:///var/run/docker.sock" >> $GITHUB_ENV

      - name: Set working directory
        run: echo "WORKING_DIR=crm_backend" >> $GITHUB_ENV

      - name: Build and test
        working-directory: ${{ env.WORKING_DIR }}
        run: ./gradlew clean test
        env:
          TESTCONTAINERS_HOST_OVERRIDE: host.testcontainers.internal
          SPRING_DATASOURCE_URL: jdbc:tc:postgresql:15:///testdb
          SPRING_PROFILES_ACTIVE: test
          SPRING_REDIS_HOST: localhost
          SPRING_REDIS_PORT: 6379

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: crm_backend/build/reports/**/*
