name: Gradle CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SPRING_PROFILES_ACTIVE: test

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      # Для Testcontainers не потрібно, але як приклад додано Redis
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test with Gradle
        run: ./gradlew clean test
        env:
          # Налаштування для Testcontainers
          TESTCONTAINERS_HOST_OVERRIDE: host.testcontainers.internal
          TESTCONTAINERS_RYUK_DISABLED: true

          # Налаштування Spring Boot
          SPRING_DATASOURCE_URL: jdbc:tc:postgresql:15:///testdb
          SPRING_DATASOURCE_USERNAME: test
          SPRING_DATASOURCE_PASSWORD: test
          SPRING_PROFILES_ACTIVE: test
          SPRING_REDIS_HOST: localhost
          SPRING_REDIS_PORT: 6379